import type { NextPage } from 'next';
import Head from 'next/head';

const App: NextPage = () => {
	return (
		<Head>
			<title>Punchlike - Homepage</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	);
};

export default App;
